### PR TITLE
Fixed recent issues.

### PR DESCRIPTION
**Pull request by TheUtopian**
Fixed:
1. "su" command dosen't work on browsers builder scripts.
2. Icons are not copied to the /usr/share/pixmaps

### CODE REVIEW

**Comment by TheUtopian** [comment]
@porteux, Current users already have the icons and new users will install it with the system (afaik, it's included into the ISO file).
If we add new icons we should also update **porteux-app-store-changed** file so I think there's no reason to adding old icons to the file.

**Comment by porteux** [comment]
The 3 icons that we have at the moment are there because these applications were added after PorteuX first release. If we don't copy them, old users will have broken icons.

My suggestions is to simply copy all icon files from the server, regardless. The code will be very simple and it will always work. :)

**Comment by TheUtopian** [comment]
As I know, there's no simple way to download content of specific folder from github, you'll have to download full zip and then decompress it or use external tool like "svn". So we should list all the icons somewhere. I can add them into **porteux-app-store-changed** or add **icon** option into **porteux-app-store-db.json** for each app. What do think?

**Comment by porteux** [comment]
> As I know, there's no simple way to download content of specific folder from github

You're totally right!

Adding it to `porteux-app-store-changed` would imply that we have to update this file manually? Currently this file is automatically being updated via script.

Adding an icon option into `porteux-app-store-db.json` for each app is a nice idea. My only concern is that for consistency we would probably add an icon for every app so we would eventually hit 404 on github multiple times for the apps that the icon is not on the server (because most of them are already in the system), which could slow down the process -- unless we use multiple threads, I don't know.

What you think?

**Comment by TheUtopian** [comment]
> Adding it to `porteux-app-store-changed` would imply that we have to update this file manually? Currently this file is automatically being updated via script.
> 
@porteux, It's good you say that I removed **update-list.sh** because I thought it's unnecesary, I'll return it.

About icons. I meant each app that has no default icon so we should add it only for a few apps.

**Comment by TheUtopian** [comment]
@porteux
I just realised if we add icons into **porteux-app-store-db.json** then we can remove **porteux-app-store-changed** because it already contains all script names except **module-builder.sh** and **appimage-builder.sh** but we can add it to python script.

**Comment by porteux** [comment]
Ok. Go ahead! :)

**Pull request merged**
