### PR TITLE
Little improvment

### PR DESCRIPTION
**Pull request by TheUtopian**
Now all new icons and builder scripts (except "module-builder.sh" and "appimage-builder.sh") will be read from **porteux-app-store-db.json**.

### CODE REVIEW

**Comment by porteux** [comment]
I made some tiny changes and it seems to be working nice in the main branch.

There's one thing that we could improve: even when all files are up-to-date we can still see the 'updating files...' dialog when we open the app store.

Amazing job! Thanks a lot! Gonna add you as a contributor in the thanks section :)

**Comment by TheUtopian** [comment]
@porteux, Thank you very much.
I think I found a solution. what if we add ersion option for each app and compare them in the script?
Then only file that will be updated every is the **porteux-app-store-db.json**

**Comment by porteux** [comment]
I made some changes in the app-store branch. Do you mind reviewing it for me before we merge to trunk?

Basically I'm checking if `porteux-app-store-db.json` is older than 6 hours, if so we download it from the server, otherwise we load the app store straightaway. This fixes the issue I told you about in the last message.

**Comment by TheUtopian** [comment]
@porteux, that's a great solution! I checked it on my system and it works well.
I think we could also remove `os.makedirs(ICONS_FOLDER, exist_ok=True)` (line 347 in the python file),
because the path **/usr/share/pixmaps/** already exists on the system afaik.

**Comment by porteux** [comment]
Cool! Merged to trunk/main.

Thanks once again :)

**Pull request merged**
